
exports.up = function(knex) {
    return knex.schema
        .createTable('Users', table =>{
            table.increments("user_id");
            table.text("user_email")
                .unique()
                .notNullable()
            table.text("username", 26)
                .notNullable()
            table.text("name")
                .notNullable()
            table.string("key")
                .notNullable()
            table.boolean("didAgree")
                .notNullable()
        })
        .createTable('Projects', table=>{
            table.increments("project_id")
            table.text("project_title", 128)
            table.date("date_project_created")
            table.date("date_project_changed")
            table.integer("user")
                .notNullable()
            table.foreign("user")
                .references("user_id")
                .inTable('Users')
        })
        .createTable('Code', table =>{
            table.increments("code_id")
            table.text("code_title", 128)
            table.text("raw_code", 2048),
            table.text("description", 512)
            table.date("date_code_created")
            table.date("date_code_changed")
            table.integer("project")
            table.foreign("project")
                .references("project_id")
                .inTable("Projects")
        })
        .createTable('Tag', table =>{
            table.increments("tag_id")
            table.text('tag_text', 16)
            table.text('color', 25)
                .notNullable()
            table.integer("project")
            table.foreign("project")
                .references("project_id")
                .inTable("Projects")
            table.text('hex', 9)
        })
        .createTable('Marker', table=>{
            table.increments("marker_id")
            table.integer('startRow')
            table.integer('startCol')
            table.integer('endRow')
            table.integer('endCol')
            table.integer("tag")
            table.foreign("tag")
                .references("tag_id")
                .inTable('Tag')
            table.integer('code')
            table.foreign('code')
                .references("code_id")
                .inTable("Code")
            table.date("marker_date_created")
            table.date("marker_date_changed")
        })
        .createTable('Snippet', table=>{
            table.increments("snippet_id")
            table.integer("position")
            table.text("snippet_title")
            table.text("snippet_data")
            table.integer("tag")
            table.foreign("tag")
                .references("tag_id")
                .inTable("Tag")
            table.integer("marker_reference")
            table.foreign("marker_reference")
                .references("marker_id")
                .inTable("Marker")
            table.integer('code_reference')
                .references("code_id")
                .inTable("Code")
        })
};

exports.down = function(knex) {
  return knex.schema
    .dropTableIfExists('Snippet')
    .dropTableIfExists('Marker')
    .dropTableIfExists('Tag')
    .dropTableIfExists('Code')
    .dropTableIfExists('Projects')
    .dropTableIfExists('Users')
};
